#ifndef INCLUDED_VERSION_H
#define INCLUDED_VERSION_H

#define LIBCHARDET_MAJOR_VER 1
#define LIBCHARDET_MINOR_VER 0
#define LIBCHARDET_PATCH_VER 7

#define LIBCHARDET_VERSION "1.0.7"
#define LIBCHARDET_UVERSION "001000007"
#define LIBCHARDET_LVERSION 0x01000007

#endif /* INCLUDED_VERSION_H */
